GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjI5NzA2MDk5LCJleHAiOjE2Mjk3MDYxMTR9.qJjBdmyguGsRD1d0VHAjnh8UMT26ySQEk9BbdR4vTVQ

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjI5NzA2MDUzfQ.t26eAMixOsiSfC7cjl4COMxJUPKHpP3X-liaSwemMLE"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "CUSCOD": "1409900367710",
  "PASSWORD": "7710"
}