GET https://api.cal.ap.ngrok.io/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTQwOTkzMDAwMDAxMCAgICAgICAgICAgIiwibWEiOiJQU0ZIUCIsImV4cGlyZXNJbiI6MzYwMCwiaWF0IjoxNjMwNTU2NDY1LCJleHAiOjE2MzA1NTY3NjV9.GS8lT6wTMOLYS899z8Zr_atlUTuHbgaUmMMHkkMSadk

###

DELETE https://api.cal.ap.ngrok.io/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.MTQwOTkzMDAwMDAxMCAgICAgICAgICAg.yhUTPLOCDIOlY5GFLeox9TI6uUV_C4bQ7Qo9cJWRNt0"
}

###

POST https://api.cal.ap.ngrok.io/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.MTQwOTkzMDAwMDAxMCAgICAgICAgICAg.yhUTPLOCDIOlY5GFLeox9TI6uUV_C4bQ7Qo9cJWRNt0"
}

###

POST https://api.cal.ap.ngrok.io/login
Content-Type: application/json

{
  "CUSCOD": "1409900367710",
  "PASSWORD": "7710"
}

###
GET https://api.cal.ap.ngrok.io/getcontno1/3-0000564           /PSFHP
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTQwOTkzMDAwMDAxMCAgICAgICAgICAgIiwibWEiOiJQU0ZIUCIsImV4cGlyZXNJbiI6MzYwMCwiaWF0IjoxNjMwNzQyNTQyLCJleHAiOjE2MzA3NDYxNDJ9.oeg6d6SLwpRXEr6xsjzQT4i2qUZqncOOzoIjrZkbhvg

###
GET  https://api.cal.ap.ngrok.io/loans/PSFHP/3-0000010 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTQwOTkzMDAwMDAxMCAgICAgICAgICAgIiwibWEiOiJQU0ZIUCIsImV4cGlyZXNJbiI6MzYwMCwiaWF0IjoxNjMwNTcyOTA3LCJleHAiOjE2MzA1NzY1MDd9.3VI6C8zVGimXfzgcL90xJa-KeiwhTB_ifkZQvnH_z0E

###
GET https://api.cal.ap.ngrok.io/getcusmast/1-0003380/LSFHP